#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_InlineMetric.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class InlineMetric : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\Dashboard\Pages\_InlineMetric.cshtml"
  
    var metric = DashboardMetric.Func(this);
    var className = metric == null ? "metric-null" : metric.Style.ToClassName();
    var highlighted = metric != null && metric.Highlighted ? "highlighted" : null;


            
            #line default
            #line hidden
WriteLiteral("<span data-metric=\"");


            
            #line 9 "..\..\Dashboard\Pages\_InlineMetric.cshtml"
              Write(DashboardMetric.Name);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"metric ");


            
            #line 9 "..\..\Dashboard\Pages\_InlineMetric.cshtml"
                                                   Write(className);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 9 "..\..\Dashboard\Pages\_InlineMetric.cshtml"
                                                              Write(highlighted);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 9 "..\..\Dashboard\Pages\_InlineMetric.cshtml"
                                                                             Write(metric?.Value);

            
            #line default
            #line hidden
WriteLiteral("</span>");


        }
    }
}
#pragma warning restore 1591
