#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\_Navigation.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Navigation : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\Pages\_Navigation.cshtml"
 if (NavigationMenu.Items.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <ul class=\"nav navbar-nav\">\r\n");


            
            #line 7 "..\..\Pages\_Navigation.cshtml"
         foreach (var item in NavigationMenu.Items)
        {
            var itemValue = item(this);

            if (itemValue == null) { continue; }


            
            #line default
            #line hidden
WriteLiteral("            <li class=\"");


            
            #line 13 "..\..\Pages\_Navigation.cshtml"
                   Write(itemValue.Active ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <a href=\"");


            
            #line 14 "..\..\Pages\_Navigation.cshtml"
                    Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    ");


            
            #line 15 "..\..\Pages\_Navigation.cshtml"
               Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n            </li>\r\n");


            
            #line 18 "..\..\Pages\_Navigation.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");


            
            #line 20 "..\..\Pages\_Navigation.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
