#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
    using Flash.Extensions.EventBus.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class PerPageSelector : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n");


            
            #line 6 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
 if (_pager.TotalPageCount > 1)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"btn-group paginator pull-right hidden-xs\">\r\n        <a href=\"");


            
            #line 9 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
            Write(_pager.PageUrl(_pager.CurrentPage > 1 ? _pager.CurrentPage - 1 : 0));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-default btn-sm ");


            
            #line 9 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
                                                                                                                 Write(_pager.CurrentPage == 1 ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 10 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
       Write(Strings.Paginator_Prev);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </a>\r\n        <a href=\"");


            
            #line 12 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
            Write(_pager.PageUrl(_pager.CurrentPage < _pager.TotalPageCount ? _pager.CurrentPage + 1 : 0));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-default btn-sm ");


            
            #line 12 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
                                                                                                                                     Write(_pager.CurrentPage == _pager.TotalPageCount ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 13 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
       Write(Strings.Paginator_Next);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </a>\r\n    </div>\r\n");


            
            #line 16 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<div class=\"btn-group pull-right paginator\">\r\n");


            
            #line 18 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
     foreach (var count in new[] { 10, 20, 50, 100, 500 })
    {

            
            #line default
            #line hidden
WriteLiteral("        <a class=\"btn btn-sm btn-default ");


            
            #line 20 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
                                     Write(count == _pager.RecordsPerPage ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 20 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
                                                                                         Write(count > 999 ? "visible-lg" : null);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n           href=\"");


            
            #line 21 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
            Write(_pager.RecordsPerPageUrl(count));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 21 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
                                              Write(count.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 22 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div class=\"btn-toolbar-spacer pull-right hidden-xs\"></div>\r\n<div class=\"" +
"btn-toolbar-label btn-toolbar-label-sm pull-right hidden-xs\">\r\n    ");


            
            #line 26 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
Write(Strings.PerPageSelector_ItemsPerPage);

            
            #line default
            #line hidden
WriteLiteral(":\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
