#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class SidebarMenu : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
 if (Items.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"stats\" class=\"list-group\">\r\n");


            
            #line 7 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
         foreach (var item in Items)
        {
            var itemValue = item(this);

            
            #line default
            #line hidden
WriteLiteral("            <a href=\"");


            
            #line 10 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
                Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"list-group-item ");


            
            #line 10 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
                                                        Write(itemValue.Active ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                ");


            
            #line 11 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
           Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span class=\"pull-right\">\r\n");


            
            #line 13 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
                     foreach (var metric in itemValue.GetAllMetrics())
                    {
                        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
                   Write(Html.InlineMetric(metric));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
                                                  
                    }

            
            #line default
            #line hidden
WriteLiteral("                </span>\r\n            </a>\r\n");


            
            #line 19 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");


            
            #line 21 "..\..\Dashboard\Pages\_SidebarMenu.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
