#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\_ErrorAlert.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ErrorAlert : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n<div id=\"errorAlert\" class=\"alert alert-danger alert-fixed display-none\" role=\"" +
"alert\">\r\n    <div class=\"container\">\r\n        <strong id=\"errorAlertTitle\"></str" +
"ong>\r\n        <span id=\"errorAlertMessage\"></span>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
