//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flash.Extensions.EventBus.Dashboard.AspNetCore.Dashboard.Content.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LayoutPage_Back {
            get {
                return ResourceManager.GetString("LayoutPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LayoutPage_Footer_Generatedms {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Generatedms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LayoutPage_Footer_Time {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Queues {
            get {
                return ResourceManager.GetString("NavigationMenu_Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string Paginator_Next {
            get {
                return ResourceManager.GetString("Paginator_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string Paginator_Prev {
            get {
                return ResourceManager.GetString("Paginator_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总条数 的本地化字符串。
        /// </summary>
        public static string Paginator_TotalItems {
            get {
                return ResourceManager.GetString("Paginator_TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页条数 的本地化字符串。
        /// </summary>
        public static string PerPageSelector_ItemsPerPage {
            get {
                return ResourceManager.GetString("PerPageSelector_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息内容 的本地化字符串。
        /// </summary>
        public static string QueueMessagesPage_Table_Message {
            get {
                return ResourceManager.GetString("QueueMessagesPage_Table_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息Id 的本地化字符串。
        /// </summary>
        public static string QueueMessagesPage_Table_MessageId {
            get {
                return ResourceManager.GetString("QueueMessagesPage_Table_MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息来源 的本地化字符串。
        /// </summary>
        public static string QueueMessagesPage_Table_NormalQueueName {
            get {
                return ResourceManager.GetString("QueueMessagesPage_Table_NormalQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueueSidebarMenu_Failed {
            get {
                return ResourceManager.GetString("QueueSidebarMenu_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueueSidebarMenu_Normal {
            get {
                return ResourceManager.GetString("QueueSidebarMenu_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueueSidebarMenu_Retry {
            get {
                return ResourceManager.GetString("QueueSidebarMenu_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueuesPage_FailedQueues {
            get {
                return ResourceManager.GetString("QueuesPage_FailedQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueuesPage_NoMessages {
            get {
                return ResourceManager.GetString("QueuesPage_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueuesPage_NoQueues {
            get {
                return ResourceManager.GetString("QueuesPage_NoQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueuesPage_NormalQueues {
            get {
                return ResourceManager.GetString("QueuesPage_NormalQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueuesPage_RetryQueues {
            get {
                return ResourceManager.GetString("QueuesPage_RetryQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueuesPage_Table_Messages {
            get {
                return ResourceManager.GetString("QueuesPage_Table_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string QueuesPage_Table_Queue {
            get {
                return ResourceManager.GetString("QueuesPage_Table_Queue", resourceCulture);
            }
        }
    }
}
