#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Paginator.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\_Paginator.cshtml"
    using Flash.Extensions.EventBus.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Paginator : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("<div class=\"btn-toolbar\">\r\n");


            
            #line 6 "..\..\Dashboard\Pages\_Paginator.cshtml"
     if (_pager.TotalPageCount > 1)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"btn-group paginator\">\r\n");


            
            #line 9 "..\..\Dashboard\Pages\_Paginator.cshtml"
             foreach (var page in _pager.PagerItems)
            {
                switch (page.Type)
                {
                    case Pager.ItemType.Page:

            
            #line default
            #line hidden
WriteLiteral("                        <a href=\"");


            
            #line 14 "..\..\Dashboard\Pages\_Paginator.cshtml"
                            Write(_pager.PageUrl(page.PageIndex));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-default ");


            
            #line 14 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                     Write(_pager.CurrentPage == page.PageIndex ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 15 "..\..\Dashboard\Pages\_Paginator.cshtml"
                       Write(page.PageIndex);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n");


            
            #line 17 "..\..\Dashboard\Pages\_Paginator.cshtml"
                        break;
                    case Pager.ItemType.NextPage:

            
            #line default
            #line hidden
WriteLiteral("                        <a href=\"");


            
            #line 19 "..\..\Dashboard\Pages\_Paginator.cshtml"
                            Write(_pager.PageUrl(page.PageIndex));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-default ");


            
            #line 19 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                     Write(page.Disabled ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 20 "..\..\Dashboard\Pages\_Paginator.cshtml"
                       Write(Strings.Paginator_Next);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n");


            
            #line 22 "..\..\Dashboard\Pages\_Paginator.cshtml"
                        break;
                    case Pager.ItemType.PrevPage:

            
            #line default
            #line hidden
WriteLiteral("                        <a href=\"");


            
            #line 24 "..\..\Dashboard\Pages\_Paginator.cshtml"
                            Write(_pager.PageUrl(page.PageIndex));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-default ");


            
            #line 24 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                     Write(page.Disabled ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 25 "..\..\Dashboard\Pages\_Paginator.cshtml"
                       Write(Strings.Paginator_Prev);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n");


            
            #line 27 "..\..\Dashboard\Pages\_Paginator.cshtml"
                        break;
                    case Pager.ItemType.MorePage:

            
            #line default
            #line hidden
WriteLiteral("                        <a href=\"#\" class=\"btn btn-default disabled\">\r\n          " +
"                  …\r\n                        </a>\r\n");


            
            #line 32 "..\..\Dashboard\Pages\_Paginator.cshtml"
                        break;
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");



WriteLiteral("        <div class=\"btn-toolbar-spacer\"></div>\r\n");


            
            #line 37 "..\..\Dashboard\Pages\_Paginator.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"btn-toolbar-label\">\r\n        ");


            
            #line 40 "..\..\Dashboard\Pages\_Paginator.cshtml"
   Write(Strings.Paginator_TotalItems);

            
            #line default
            #line hidden
WriteLiteral(": ");


            
            #line 40 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                  Write(_pager.TotalRecordCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
