#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 3 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.Linq;
    
    #line 4 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using Flash.Extensions.EventBus.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using Flash.Extensions.EventBus.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");








WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html lang=\"");


            
            #line 12 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       Write(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n<head>\r\n    <title>");


            
            #line 14 "..\..\Dashboard\Pages\LayoutPage.cshtml"
      Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <meta ch" +
"arset=\"utf-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-s" +
"cale=1.0\">\r\n    <meta name=\"robots\" content=\"none\">\r\n");


            
            #line 19 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       var version = GetType().GetTypeInfo().Assembly.GetName().Version; 

            
            #line default
            #line hidden
WriteLiteral("    <link rel=\"shortcut icon\" href=\"data:image/x-icon;,\" type=\"image/x-icon\">\r\n  " +
"  <link rel=\"stylesheet\" href=\"");


            
            #line 21 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                            Write(Url.To($"/css{version.Major}{version.Minor}{version.Build}0"));

            
            #line default
            #line hidden
WriteLiteral(@""">
</head>
<body>
    <div id=""wrap"">
        <!-- Fixed navbar -->
        <div class=""navbar navbar-default navbar-fixed-top"">
            <div class=""container"">
                <div class=""navbar-header"">
                    <button type=""button"" class=""navbar-toggle"" data-toggle=""collapse"" data-target="".navbar-collapse"">
                        <span class=""icon-bar""></span>
                        <span class=""icon-bar""></span>
                        <span class=""icon-bar""></span>
                    </button>
                    <a class=""navbar-brand"" href=""");


            
            #line 34 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                             Write(Url.Home());

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 34 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                                          Write(Html.Raw(DashboardOptions.DashboardTitle));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </div>\r\n                <div class=\"collapse navbar-collaps" +
"e\">\r\n                    ");


            
            #line 37 "..\..\Dashboard\Pages\LayoutPage.cshtml"
               Write(Html.RenderPartial(new Navigation()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 38 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                     if (@AppPath != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <ul class=\"nav navbar-nav navbar-right\">\r\n               " +
"             <li>\r\n                                <a href=\"");


            
            #line 42 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                    Write(AppPath);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                    <span class=\"glyphicon glyphicon-log-out\"" +
"></span>\r\n                                    <span class=\"hidden-sm\">\r\n        " +
"                                ");


            
            #line 45 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                   Write(Strings.LayoutPage_Back);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </span>\r\n                                </" +
"a>\r\n                            </li>\r\n                        </ul>\r\n");


            
            #line 50 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n                <!--/.nav-collapse -->\r\n            </div" +
">\r\n            <!-- Error alert when polling fails -->\r\n            ");


            
            #line 55 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       Write(Html.RenderPartial(new ErrorAlert()));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <!-- Begin page content -->\r\n        <div class=\"cont" +
"ainer js-page-container margin-bottom-20p\">\r\n            ");


            
            #line 60 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>
    </div>
    <div id=""footer"">
        <div class=""container"">
            <ul class=""list-inline credit"">
                <li>
                    <a href=""https://www.hangfire.io/"" target=""_blank"" rel=""noopener noreferrer"">
                        EventBus Dashboard ");


            
            #line 68 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                       Write($"{version.Major}.{version.Minor}.{version.Build}");

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n                </li>\r\n                <li>");


            
            #line 71 "..\..\Dashboard\Pages\LayoutPage.cshtml"
               Write(Strings.LayoutPage_Footer_Time);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 71 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                               Write(Html.LocalTime(DateTime.UtcNow));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                <li>");


            
            #line 72 "..\..\Dashboard\Pages\LayoutPage.cshtml"
               Write(String.Format(Strings.LayoutPage_Footer_Generatedms, GenerationTime.Elapsed.TotalMilliseconds.ToString("N")));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    <script src=\"");


            
            #line 76 "..\..\Dashboard\Pages\LayoutPage.cshtml"
            Write(Url.To($"/js{version.Major}{version.Minor}{version.Build}0"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
