#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash.Extensions.EventBus.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
    using Flash.Extensions.EventBus.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
    using Flash.Extensions.EventBus.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
    using Flash.Extensions.EventBus.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class QueueMessagePage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
  
    Layout = new LayoutPage(Strings.NavigationMenu_Queues);
    var list = this.Monitor.GetMessages(this.Queue).ConfigureAwait(false).GetAwaiter().GetResult();


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h1 class=\"page-header\"" +
">");


            
            #line 13 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                           Write(this.Queue);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


            
            #line 14 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
         if (list.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-success\">\r\n                ");


            
            #line 17 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
           Write(Strings.QueuesPage_NoMessages);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 19 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""js-jobs-list"">
                <div class=""table-responsive"">
                    <table class=""table table-striped"">
                        <thead>
                            <tr>
                                <th class=""min-width-200p"">");


            
            #line 27 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                                                      Write(Strings.QueueMessagesPage_Table_MessageId);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 28 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                               Write(Strings.QueueMessagesPage_Table_NormalQueueName);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 29 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                               Write(Strings.QueueMessagesPage_Table_Message);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            </tr>\r\n                        </thead>\r\n     " +
"                   <tbody>\r\n");


            
            #line 33 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                             foreach (var queue in list)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>");


            
            #line 36 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                                   Write(queue.MessageId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>");


            
            #line 37 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                                   Write(queue.NormalQueueName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>");


            
            #line 38 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                                   Write(queue.Message);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n");


            
            #line 40 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n            </div>\r\n");


            
            #line 45 "..\..\Dashboard\Pages\QueueMessagePage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
